name: CI

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]
  workflow_dispatch:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build and Test (Java 21) on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest ]

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      - name: Make mvnw executable (Unix)
        if: runner.os != 'Windows'
        run: chmod +x mvnw

      - name: Build and test (Unix)
        if: runner.os != 'Windows'
        run: ./mvnw -q --batch-mode --no-transfer-progress verify

      - name: Build and test (Windows)
        if: runner.os == 'Windows'
        run: .\mvnw.cmd -q -B -ntp verify

      - name: Upload test reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: surefire-reports-${{ matrix.os }}
          path: |
            **/target/surefire-reports/*.txt
            **/target/surefire-reports/*.xml
            **/target/failsafe-reports/*.txt
            **/target/failsafe-reports/*.xml
